---
- name: Mitigation for OpenSSH daemon vulnerability CVE-2024-6387
  hosts: all
  remote_user: ansible
  become: true

  tasks:
    - name: Remove LoginGraceTime
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#?LoginGraceTime\s+.*$'
        state: absent

    # ========= IN-PLACE PATCH =========
    # - name: Set LoginGraceTime to 0
    #   ansible.builtin.lineinfile:
    #     path: /etc/ssh/sshd_config
    #     line: LoginGraceTime 0
    #     state: present
    #     firstmatch: true
    #     insertbefore: ".*Match.*"
    #   notify:
    #     - "Restart SSHd"
    - name: Set LoginGraceTime to 0 (drop-in)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/99-cve-2024-6387-mitigation.conf
        line: LoginGraceTime 0
        state: present
        create: true
      notify:
        - "Restart SSHd"

    - name: Verify SSHd configuration
      ansible.builtin.command: sshd -t
      register: sshd_config_valid
      failed_when: sshd_config_valid.rc != 0

  handlers:
    - name: Restart SSHd
      ansible.builtin.systemd_service:
        name: sshd
        state: restarted
      when: sshd_config_valid
